const GLOBALS = {
  API_STATUSES: {
    NOT_CALLED: 'NOT_CALLED',
    REQUEST: 'REQUEST',
    SUCCESS: 'SUCCESS',
    FAILURE: 'FAILURE',
    TIMEOUT: 'TIMEOUT',
  },

  TOAST_TIMEOUT: 5000,

  DEFAULT_OFFSET: 0,
  DEFAULT_LIMIT: 30,
};

export default GLOBALS;
