const uiTypes = {
  GET_MENUS_REQUEST: 'GET_MENUS_REQUEST',
  GET_MENUS_SUCCESS: 'GET_MENUS_SUCCESS',
  GET_MENUS_FAILURE: 'GET_MENUS_FAILURE',

  GET_FOOTER_LINKS_REQUEST: 'GET_FOOTER_LINKS_REQUEST',
  GET_FOOTER_LINKS_SUCCESS: 'GET_FOOTER_LINKS_SUCCESS',
  GET_FOOTER_LINKS_FAILURE: 'GET_FOOTER_LINKS_FAILURE',
};

export default uiTypes;
