export default {
  SHOW_TOAST: 'SHOW_TOAST',
  SHOW_INFO_TOAST: 'SHOW_INFO_TOAST',
  SHOW_SUCCESS_TOAST: 'SHOW_SUCCESS_TOAST',
  SHOW_WARNING_TOAST: 'SHOW_WARNING_TOAST',
  SHOW_ERROR_TOAST: 'SHOW_ERROR_TOAST',

  SHOW_ALERT: 'SHOW_ALERT',
  SHOW_INFO_ALERT: 'SHOW_INFO_ALERT',
  SHOW_SUCCESS_ALERT: 'SHOW_SUCCESS_ALERT',
  SHOW_WARNING_ALERT: 'SHOW_WARNING_ALERT',
  SHOW_ERROR_ALERT: 'SHOW_ERROR_ALERT',

  REMOVE_TOAST: 'REMOVE_TOAST',
  CLEAR_ALERT: 'CLEAR_ALERT',
};
